# Generated by Django 4.1.4 on 2023-07-19 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_registertrainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.registertrainer'),
        ),
        migrations.RemoveField(
            model_name='registertrainer',
            name='clients',
        ),
        migrations.AddField(
            model_name='registertrainer',
            name='clients',
            field=models.ManyToManyField(related_name='trainers', to='gym.registeruser'),
        ),
    ]
