# Generated by Django 4.1.4 on 2023-07-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_rename_registeruser_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
