# Generated by Django 4.1.4 on 2023-07-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_member_registered_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
