# Generated by Django 4.2.3 on 2023-07-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_alter_trainer_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='skills',
            field=models.CharField(choices=[('Kickboxing', 'Kickboxing'), ('Boxing', 'Boxing'), ('Mma', 'Mma'), ('Weightlifting', 'Weightlifting'), ('Cardio', (('CYCLING', 'Cycling'), ('RUNNING', 'Running'), ('SWIMMING', 'Swimming'), ('EXPLOSIVE', 'Explosive strength'))), ('Crossfit', 'Crossfit')], default='Weightlifting', max_length=255),
        ),
    ]
