# Generated by Django 4.2.3 on 2023-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_alter_trainer_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
