# Generated by Django 4.2.3 on 2023-07-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_trainer_registered_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='skills',
        ),
        migrations.CreateModel(
            name='SkillChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainer')),
            ],
        ),
    ]
