# Generated by Django 4.2.3 on 2023-07-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_remove_trainer_skills_skillchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='skills',
            field=models.ManyToManyField(to='gym.skillchoices'),
        ),
    ]
