# Generated by Django 4.2.3 on 2023-07-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_trainer_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillchoices',
            name='assigned_to',
        ),
    ]
